export const notaSituation = [
  {
    name: 'Obras não executadas e/ou canceladas (reprogramar)',
    sigla: 'CA',
    id: 1,
    color1: '#ee33333f',
    color: '#ee3333',
  },
  {
    name: 'Atenção (ver comentário',
    sigla: 'RE',
    id: 2,
    color1: '#65d16a36',
    color: '#65d16a',
  },
  {
    name: 'Documento SPiR emitido',
    sigla: 'AT',
    id: 3,
    color1: '#8ef7e936',
    color: '#8ef7e9',
  },
  {
    name: 'Documento SPiR Emitido / SAP e lista Ok',
    sigla: 'D',
    id: 4,
    color1: '#5495bb34',
    color: '#5495bb',
  },
  {
    name: 'Documento SPiR com problema',
    sigla: 'DA',
    id: 5,
    color1: '#3c73923a',
    color: '#3c7392',
  },
  {
    name: 'Já lançadas no SGDO (documentos SPiR emitido)',
    sigla: 'L',
    id: 6,
    color1: '#1f2e7036',
    color: '#1f2e70',
  },
  {
    name: 'Já lançadas no SGDO (falta tratativas trânsito/outros',
    sigla: 'LT',
    id: 7,
    color1: '#0a12853a',
    color: '#0a1285',
  },
  {
    name: 'Aguarda estorno logística',
    sigla: 'E',
    id: 8,
    color1: '#cea1273d',
    color: '#cea127',
  },
  {
    name: 'Erro ao carregar nota no SGDO',
    sigla: 'EC',
    id: 9,
    color1: '#615f5f36',
    color: '#615f5f',
  },
  {
    name: 'Tratar com comitê (obras complexas',
    sigla: 'CM',
    id: 10,
    color1: '#034e223a',
    color: '#034e22',
  },
  {
    name: 'Equipe não disponível',
    sigla: 'ND',
    id: 11,
    color1: '#1414143d',
    color: '#141414',
  },
  {
    name: 'Provisão (PR) e/ou Repasse',
    sigla: 'PR',
    id: 12,
    color1: '#607f833a',
    color: '#607f83',
  },
]
